server:
  port: 0   # pick a random free port

spring:
  application:
    name: airtel-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
